name: flutter_base
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.9.0'

dependencies:
  # BASE
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # AAA
  auto_route: ^11.0.0
  app_tracking_transparency: ^2.0.6

  # BBB
  # CCC
  collection: ^1.19.1
  # DDD
  device_info_plus: ^12.3.0

  # EEE
  # FFF
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.1.0
  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5
  firebase_messaging: ^16.0.0
  fluttertoast: ^9.0.0
  flutter_ads:
    git:
      url: https://bitbucket.org/innofyapp/flutter_ads.git
      ref: version/1.4.1

  flutter_iap:
    git:
      url: https://bitbucket.org/innofyapp/flutter_iap.git
      ref: version/1.2.2

  # ggg
  get_it: ^9.1.1
  gma_mediation_meta: ^1.4.1

  # HHH
  hydrated_bloc: ^10.1.1

  # III
  injectable: ^2.3.2
  in_app_review: ^2.0.8
  iabtcf_consent_info: ^3.4.0
  intl: ^0.20.2
  # JJJ
  json_annotation: ^4.8.1
  # KKK

  # LLL
  logger: ^2.0.2+1
  lottie: ^3.1.2

  # MMM
  marquee: ^2.2.3
  # NNN
  # OOO
  # PPP
  package_info_plus: ^9.0.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  # QQQ
  quick_actions: ^1.1.0
  # RRR
  # SSS
  shared_preferences: ^2.2.2
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  # TTT
  # UUU
  url_launcher: ^6.2.5
  upgrader: ^12.3.0
  # VVV
  # WWW
  # XXX
  # YYY
  # ZZZ

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.15
  injectable_generator: ^2.6.1
  auto_route_generator:
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.11.0
  # Flavor
  flutter_flavorizr: ^2.3.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/rates/
    - assets/images/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/languages/
    - assets/lottie/

#  fonts:
#    - family: OpenSans
#      fonts:
#        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf

#generate
flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    outputs:
      class_name: Assets